version: '3'
services:
  angular:
    container_name: aurora
    image: aurora
    build: .
    volumes:
      - /app/node_modules
      - .:/app

    ports:
      - "8100:8100"
      - "8200:8200"
      - "49153:49153"
